Add rubocop
HeavyTechRuby/versus pull request #18
Opened 2024-06-12 04:08 UTC by onishchenko-va

Pre-commit реализовал через gem [overcommit](https://github.com/sds/overcommit)

2024-06-12 09:15 UTC, sergio-fry requested changes

2024-06-12 09:15 UTC, sergio-fry commented on .overcommit.yml
> +PreCommit:
Я правильно понимаю, что проверка не даст запушить код, если rubocop не пройден? В этом случае, мы лишаем возможности показать промежуточный результат в PR. И это замедляет процесс комитов, что доставляет мелкий дискомфорт. 

При этом, мы и так не примем PR, который не прошел все проверки. 

Как считаешь?

2024-06-13 03:20 UTC, onishchenko-va commented on .overcommit.yml
> +PreCommit:
Да, это так. 

Опционально можно поправить через:
  on_fail: warn
в конфиге overcommit-а.

Это позволит выводить ошибки, как предупреждения на pre-commit-e с выполнением commit-а.    


Есть вопрос по поводу: 

-   [rubocop-rails](https://rubygems.org/gems/rubocop-rails)
-   [rubocop-rspec](https://rubygems.org/gems/rubocop-rspec)
-   [rubocop-rspec_rails](https://rubygems.org/gems/rubocop-rspec_rails)
-   [rubocop-capybara](https://rubygems.org/gems/rubocop-capybara)

нужны ли они нам?

2024-06-13 14:08 UTC, sergio-fry commented on .overcommit.yml
> +PreCommit:
Я бы хотел отказаться от использования хуков, по причине описанной выше. gem-ы нужны, как мне кажется, так как мы эти библиотеки используем

2024-06-14 01:53 UTC, onishchenko-va commented on .overcommit.yml
> +PreCommit:
Хорошо, не проблем)).  Просто, из контеста задачи ("На каждый коммит должна запускать проверка lint rubocop") я понил, что запуск rubocop-а должен быть автоматизированным. Спасибо за фидбэк).

2024-06-14 07:50 UTC, sergio-fry approved these changes

2024-06-14 07:51 UTC, sergio-fry commented on .overcommit.yml
> +PreCommit:
понял, ввел тебя в заблуждение

2024-06-14 07:52 UTC, sergio-fry requested changes
Необходимо встроить проверку в CI

2024-06-17 08:32 UTC, sergio-fry requested changes
падает сборка

2024-06-17 12:12 UTC, onishchenko-va commented
Судя по логам выполнения actions, падало на проверке кода линтером. Подправил.

2024-06-17 13:10 UTC, sergio-fry requested changes

2024-06-17 13:10 UTC, sergio-fry commented on Rakefile
> +# frozen_string_literal: true
Вот тут прошу настроить так, чтобы было запрещено использовать этот frozen_literal строку.

2024-08-07 18:33 UTC, sergio-fry approved these changes

2024-08-07 18:33 UTC, merged