Feature/issue 7 authentication
HeavyTechRuby/versus pull request #20
Opened 2024-09-07 13:56 UTC by Keallar

Решается issue #7

2024-09-09 07:23 UTC, sergio-fry requested changes

2024-09-09 07:23 UTC, sergio-fry commented on .rspec
> ---require spec_helper
я бы хотел оставить spec_helper по-умолчнию, чтобы иметь возможность писать быстрые тесты. Иначе у нас каждый тест, даже который не требует rails будет ее грузить

2024-09-09 07:23 UTC, sergio-fry commented on .rubocop.yml
> +Style/FetchEnvVar:
А почему предлагаешь это отключить?

2024-09-09 07:23 UTC, sergio-fry commented on app/controllers/users/omniauth_callbacks_controller.rb
> +        session['devise.github_data'] = request.env['omniauth.auth'].except(:extra)
а как потом это используется? нигде не могу найти github_data

2024-09-09 07:23 UTC, sergio-fry commented on spec/factories/competition.rb
> +    name { Faker::Lorem.word }
Рандом в тестах нежелателен, лучше простые тексты. Если важная уникальность, то лучше добавлять индекс через sequence.

2024-09-09 07:23 UTC, sergio-fry commented on spec/factories/user.rb
> +    email { Faker::Internet.email }
тут тоже

2024-09-09 07:23 UTC, sergio-fry commented on spec/rails_helper.rb
> +    OmniAuth.config.add_mock(:github, OmniAuth::AuthHash.new(Faker::Omniauth.github))
а можем это не глобально добавить, а только для выбранных тестов?

2024-09-15 10:15 UTC, Keallar commented on .rubocop.yml
> +Style/FetchEnvVar:
Забыл убрать. Считаю не стоит отключать

2024-09-15 10:49 UTC, Keallar commented on app/controllers/users/omniauth_callbacks_controller.rb
> +        session['devise.github_data'] = request.env['omniauth.auth'].except(:extra)
Пока нигде. Думаю стоит убрать, так как пока что не предполагается предварительно вставлять данные пользователя на форму регистрации после неудачной аутенфикации

2024-09-20 09:30 UTC, Keallar commented
@sergio-fry запрашиваю повторное ревью

2024-09-20 10:14 UTC, sergio-fry requested changes

2024-09-20 10:14 UTC, sergio-fry commented on Gemfile
> +  gem 'faker'
Вот это давай вообще не будем использовать, так как это рандом в тестах - как и писал выше

2024-09-20 10:14 UTC, sergio-fry commented on spec/factories/competition.rb
> +    description { Faker::Lorem.sentence }
нужно без рандома

2024-09-20 10:14 UTC, sergio-fry commented on spec/factories/user.rb
> +    username { Faker::FunnyName.name }
нужно без рандома

2024-09-20 10:14 UTC, sergio-fry commented on spec/factories/user.rb
> +    name { Faker::Name.name }
нужно без рандома

2024-09-20 10:14 UTC, sergio-fry commented
Остается только fake убрать. В остальном - ОК

2024-09-20 10:15 UTC, Keallar commented
Окей, сегодня тогда уберу

2024-09-23 07:50 UTC, sergio-fry approved these changes

2024-09-23 07:51 UTC, merged